<?php
echo '<?xml version="1.0" encoding="UTF-8" />';
echo $this->doctype();
$config = Zend_Registry::get ( "config" );
?>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>FLLHAUS Direct booking system</title>
<meta name="description" content="FLLHAUS Direct booking system" />
    <?php
				$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/default.css' );
				$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/fancy.css' );
				$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/slide.css' );
				
				$this->headScript ()->prependFile ( $config->baseurl . '/js/menuslide/slide.js' );
				$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.easing.1.3.js' );
				$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.tools.min.js' );
				$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.fancybox-1.3.4.pack.js' );
				$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery-1.4.3.min.js' );
				echo $this->headLink ();
				?>
	
</head>

<body>
<?php
echo $this->layout ()->content;
?>
</body>

<?php
    echo $this->headScript ();
    ?>  
<!--Fancybox options-->
<script type="text/javascript">
    jQuery(document).ready(function($) {
     //   $(".download").tooltip({ position: 'center right',delay: '0', offset: [0, -30]});
       
        $("a.zoom3").fancybox();
        /*
        $("a.zoom1").fancybox({
                'overlayOpacity'    :   0.5,
                'frameWidth'        :   500,
                'frameHeight'       :   600,
                'overlayColor'      :   '#000'
            });

            $("a.zoom2").fancybox({
                'zoomSpeedIn'       :   500,
                'zoomSpeedOut'      :   500
            });  
            $("a.zoom3").fancybox({
                'zoomOpacity'       :   1000,
                'overlayOpacity'    :   0.3,
                'zoomSpeedIn'       :   500,
                'zoomSpeedOut'      :   200,
                'frameWidth'        :   800,
                'overlayColor'      :   '#000',
                'padding'           :   0,
                'frameHeight'       :   600,
                'autoDimensions'    :   false
                
                
            });

         */ 
        });
    </script>
