<!--Start Sliding MenuPanel--> 
<div id="toppanel">

<div id="Head">
<div id="Logo"></div>

<div id="ServerTime">
<ul class="login">
<li id="clock" class="Time"></li>
</ul>
</div>

<div id="ToggleMenu">
<ul class="login">
<li><br /></li>
<li class="sep"></li>
<li id="toggle">
<a id="open" class="open" href="#">Open Menu</a>
<a id="close" style="display: none;" class="close" href="#">Close Menu</a
></li>
</ul>
</div>
</div>


<!--Start MenuPanel Content--> 
<div id="panel">

<!--Start Panel Content - Clearfix with logo and content divs--> 
<div class="content clearfix">






<div id="Testpanel">
<div id="LoggedIn">
<div id="LoggedInTitle">
<input type="text" name="name" id="name" value="Search..."/>
</div>
<ul id="flowtabs">
    <li><a id="1" href="#1">Administration</a></li>
    <li><a id="2" href="#2">Frontdesk</a></li>
    <li><a id="3" href="#3">Reports</a></li>
    <li><a id="4" href="#4">Statistics</a></li>
</ul>
</div>



<!-- tabs work as navigator for scrollable -->


<!-- panes -->
<div id="flowpanes">


    <!-- wrapper for scrollable items -->
<div class="items">

<div>
<div id="MenuDivTitle">
<h2>Administration</h2>
</div>
<div id="MenuDiv">
<ul>
<li><a class="zoom3" href="hotel/add">Add Property</a></li>
<li><a class="zoom3" href="templates/tmp_editroomcat.html?iframe">add Roomcategory</a></li>
<li></li>
</ul>
</div>
<div id="MenuDiv">
<ul>
<li></li>
</ul>
</div>
<div id="MenuDiv">
<ul>
<li></li>
</ul>
</div>
</div>

<div>
<div id="MenuDivTitle">
<h2>Frontdesk</h2>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
</div>

<div>
<div id="MenuDivTitle">
<h2>Rapporter</h2>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
</div>


<div>
<div id="MenuDivTitle">
<h2>Statistik</h2>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
<div id="MenuDiv">
<li></li>
</div>
</div>





</div>


</div>

<!-- activate tabs with JavaScript -->
<script>


// wait until document is fully scriptable
$(document).ready(function() {

    // select #flowplanes and make it scrollable. use circular and navigator plugins
    $("#flowpanes").scrollable({size: 1, clickable: false})
    .mousewheel(400) 

    .navigator({

        // select #flowtabs to be used as navigator
        navi: "#flowtabs",
        // select A tags inside the navigator to work as items (not direct children)
        naviItem: 'a',
        
        // assign "current" class name for the active A tag inside navigator
        activeClass: 'current'
        


    });

});
</script>




</div>



  


</div>
<!--Start Panel Content - Clearfix with logo and content divs--> 

</div>
<!--End MenuPanel Content--> 




<!--Start Tab - Menu Panel Up/down-->  
<div class="tab">
        <ul class="login">
            <li class="left">&nbsp;</li>
            <?php $loggedInUser = $this->loggedInUser()?>
            <li>
            <?php echo empty($loggedInUser) ? "" : $loggedInUser->first_name." ".$loggedInUser->last_name?>
            </li>
            <li class="sep">|</li>
            <li>
            <?php echo $this->pageModel->hotel->name?>
            </li>
            <li class="sep">|</li>
            <li class="right">&nbsp;</li>
        </ul> 
    </div>
<!--End Tab - Menu Panel Up/down--> 
    
</div>
<!--End Sliding MenuPanel--> 


<div id="Container">
<div id="Header"></div>
<?php 
$rooms = $this->pageModel->getHotelRooms();
?>
<div id="Availability">
<div id="PanelHead"><h1>Availability</h1><p> Occ:<span class="HeadInfo">00,0%</span>Rate:<span class="HeadInfo">Std</span>Currency:<span class="HeadInfo">SEK</span></p></div>
<div id="PanelContent">


<?php 
foreach($rooms as $room) {
?>
<ul class="Link"> 
<li >
<span class="LeftSpace">
<form>
    <input type="hidden" name="room_id" value="<?php echo $room->id?>"></input>
    <input name="Available" type="text" id="Available" value="<?php echo $room->available?>" />
</form>
</span>
<span class="RightSpace">
<h3>Roomcategory</h3>
<p>Discount:<span class="DiscComCol"><?php echo Room::getDiscount($room)?></span>commission:<span class="DiscComCol">15%</span></p>
</span>
</li>
</ul>
<?php }//end foreach?> 
</div>

<div id="AvailTotal">
 <ul class="Link"> 
<li>
  <span class="LeftSpace">
  <p>0</p></span>
  <span class="RightSpace">
  <h3>Total available</h3></span>
</li>
</ul>
</div>

<div id="PanelInfo">Showing <span class="StatusCol">1-5</span> Categories of <span class="StatusCol">99</span> | <span class="ShowMore"><a href="#">Previous</a> <a href="#">Next</a></span></div>

<div id="PanelFoot"><a href="">Edit Availability</a><a href="">Edit All</a></div>

</div>





<div id="Reservations">
<div id="PanelHead">
<h1>bookings in</h1>
<p>Today:<span class="HeadInfo">0</span>Pending:<span class="HeadInfo">0</span></p></div>
<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>



</div>
<div id="PanelInfo">Showing <span class="StatusCol">1-3</span> Bookings of <span class="StatusCol">99</span> | <span class="ShowMore"><a href="#">Previous</a> <a href="#">Next</a></span></div>
<div id="PanelFoot"><a href="">Show Pending</a><a href="">Show All</a></div>
</div>





<div id="Requests">

<div id="PanelHead">
<h1>bookings out</h1><p>Today:<span class="HeadInfo">0</span>Pending:<span class="HeadInfo">0</span></p>
</div>


<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>Time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

</div>


<div id="PanelInfo">Showing <span class="StatusCol">1-3</span> Bookings of <span class="StatusCol">99</span> | <span class="ShowMore"><a href="#">Previous</a> <a href="#">Next</a></span></div>

<div id="PanelFoot"><a href="">New Booking</a><a href="">Show Today</a></div>

</div>





<div id="Summary">
<div id="PanelHead"><h1>Summary</h1>
<p>City:<span class="HeadInfo">Stockholm</span>Area:<span class="HeadInfo">north</span></p></div>
<div id="PanelContent">

<ul class="Summary"> 
<li>
  <span class="LeftSpace">
  <p>0</p>
  <p>0</p>
  <p>0.0%</p>
  <p>&nbsp;</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  </span>
  <span class="RightSpace">
  <p>Total amount of rooms</p>
  <p>Total amount of Hotels</p>
  <p>Occupancy</p>
  <p>&nbsp;</p>
  <p>Available rooms</p>
  <p>available hotels</p>
  </span></li>
<li><span class="RightSpace">
  <p>Occupied rooms</p>
  <p>Full hotels</p>
  <p>Overbooked rooms</p>
  <p>Overbooked hotels</p>
  </span>
</li>
</ul>
</div>
<div id="PanelFoot"><a href="">Summary view</a><a href="">Area view</a></div>
</div>





<div id="Warnings">
<div id="PanelHead">
<h1>Warnings</h1>
<p>Today:<span class="HeadInfo">0</span>New:<span class="HeadInfo">0</span></p>
</div>
<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3 class="InfoCol">Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>






</div>
<div id="PanelInfo">Showing <span class="StatusCol">1-3</span> Warnings of <span class="StatusCol">99</span> | <span class="ShowMore"><a href="#">Previous</a> <a href="#">Next</a></span></div>
<div id="PanelFoot"><a href="">New warning</a><a href="">Show Today</a></div>
</div>







</div>