<?php 
$config = Zend_Registry::get("config");
?>
<div id="Container">
<div id="Head">
<div id="Logo">v.0.1.0</div>
<div id="Menu">
<ul>
<?php $loggedInUser = $this->loggedInUser()?>
<li class="MenuItem">
<?php echo empty($loggedInUser) ? "" : $loggedInUser->first_name." ".$loggedInUser->last_name?>
</li>
<li class="MenuItem">
<?php echo isset($this->pageModel->hotel) ? $this->pageModel->hotel->name : "No hotel"?>
</li>
<li class="MenuItem"><a href="">Administration</a></li>
<li class="MenuItem"><a href="">Frontdesk</a></li>
<li class="MenuItem"><a href="">Statistics</a></li>
<li class="MenuItem"><a href="">Reports</a></li>
<li class="MenuItem"><a href="">Misc</a></li>
<li class="MenuItem"><a href="<?php echo $this->url(array("controller"=>"user", "action"=>"logout", null, true))?>"><span class="Logut">Logout</span></a></li>
</ul>
</div>

</div>
<?php if (isset($this->pageModel->hotel)) {?>
<div id="Col1">
<div class="ColHead">
<span class="Left"><span class="HeadLine">Availability</span><span class="SubLine">Occupancy 00,0%</span></span>
<span class="Right"><span class="HeadLine">000</span><span class="SubLine">Available</span></span>
</div>

<!--
<form class="FormRooms">
  <label>
  <input name="FreeRooms" type="text"   value="0000"  maxlength="4" />
  Roomcategory<span class="small">Discount: 000  Discount: 000</span>
</label>
</form>-->



<?php 
$rooms = $this->pageModel->getHotelRooms();
?>
<ul>
<?php 
foreach ($rooms as $room) {
?>
<li class="Avail"><a class="various1" href="<?php echo $this->url(array("controller"=>"room", "action"=>"edit", "rid"=>$room->id), null, true)?>"><span class="RoomNo"><?php echo $room->available?></span><span class="HeadLine"><?php echo $room->name."(".$room->key.")"?></span><span class="DisCom"><span class="Dis">Discount:<?php echo Room::getDiscount($room)?>%</span><span class="Com">Commission: <?php echo Room::getCommission($room)?>%</span></span></a></li>
<?php }?>
</ul>



<div class="ColControl">
<p>Showing Roomcategories 1 - 9 of 9</p>
<ul>
<li><a href=""><span class="PrevIcon"></span>Prev</a></li>
<li><a href="">All</a></li>
<li><a href=""><span class="NextIcon"></span>Next</a></li>
</ul>
</div>

<div class="ColFoot">
<ul>
<li><a href=""><span class="FootButton">Edit All</span></a></li>
</ul>
</div>

</div>


<div id="Col2">
<div class="ColHead">
<span class="Left"><span class="HeadLine">Events</span><span class="SubLine">Events today: 0000</span></span>
<span class="Right"><span class="HeadLine">00:00:00</span><span class="SubLine">Wednesday, September 30</span></span>
</div>




<?php 
$bookingActivities = $this->pageModel->getBookingActivities();
echo $this->bookingOverview($bookingActivities);
?>
<!--
<div id="WrapEvent">
<ul class="Blue">
<li><a class="Win" href="templates/menu.html"><span class="Right"><span class="Time">00:00</span>
  <h3>Andersson-hjelm, sven-gördis</h3>
  <p>1 roomcategory, 1 p</p>
  <p>from: Test hotel</p></span><p class="Icon"></p><span class="Left">
  <h1>Pen</h1>EXP: 00:00</span></a></li>
</ul>
</div>-->




<div class="ColControl">
<p>Showing Events 1 - 6 of 6</p>
<ul>
<li><a href=""><span class="PrevIcon"></span>Prev</a></li>
<li><a href="">All</a></li>
<li><a href=""><span class="NextIcon"></span>Next</a></li>
</ul>
</div>

<div class="ColFoot">
<ul>
<li><a href="<?php echo $this->url(array("controller"=>"room", "action"=>"search"), null, false)?>" class="various1"><span class="FootButton">New Booking</span></a></li></ul>
</div>
</div>






<div id="Col3">
<div class="ColHead">
<span class="Left"><span class="HeadLine">Overview</span></span>
</div>

<div id="WrapDetails">
<ul>
<li class="Title"><h1>NW</h1></li>
<li class="Left"><h2>00.0%</h2></li>
<li class="Right"><h2>Occupancy</h2></li>
<li class="Left"><h2>0000</h2></li>
<li class="Right"><h2>Available rooms</h2></li>
<li class="Left"><h2>0000</h2></li>
<li class="Right"><h2>Available hotels</h2></li>
<li class="Space"></li>
<li class="Left">0000</li>
<li class="Right">Rooms Total</li>
<li class="Left">0000</li>
<li class="Right">Hotels Total</li>
<li class="Left">0000</li>
<li class="Right">rooms Overbooked</li>
<li class="Left">0000</li>
<li class="Right">Hotels Overbooked</li>
<li class="Left">0000</li>
<li class="Right">Hotels Full</li>
</ul>
</div>

<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">NW</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">N</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">NE</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">W</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">City</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">NE</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">SW</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">s</span>0000</a></li></ul>
<ul class="WrapArea"><li class="Link"><a href=""><span class="Area">SE</span>0000</a></li></ul>

<div id="WrapCity"><a href=""><span class="Area">Stockholm</span>0000</a></div>


<div class="ColFoot">
<ul>
<li><a href=""><span class="FootButton">Favourites</span></a></li></ul>
</div>
</div>
<?php }?>
</div>

<div style="display:none">
<div id="AvailOneWrap">
<p class="RoomCatName">Roomcategory</p>

<ul class="ValDesc">
<li class="ValName">&nbsp;</li>
<li>Available rooms</li>
<li>Discount:</li>
<li>Commission:</li>
</ul>

<ul class="CurVal">
<li class="ValName">Current Value:</li>
<li>0</li>
<li>000</li>
<li>00%</li>
</ul>

<ul class="NewVal">
<li class="ValName">New Value:</li>
<li><input name="Rooms" type="text" class="FormAvailRoom" value="0" size="5" maxlength="5" /></li>
<li><input name="Discount" type="text" class="FormAvailRoom" value="0" size="5" maxlength="8" /></li>
<li><input name="Commission" type="text" class="FormAvailRoom" value="0" size="5" maxlength="2" /></li>
</ul>

<ul class="ButtonUl">
<li class="ValName">&nbsp;</li>
<li>&nbsp;</li>
<li><a href=""><span class="Button">Save</span></a></li>
<li><a href=""><span class="Button">close</span></a></li>
</ul>

</div>
</div>
