<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!--Start Sliding MenuPanel--> 
<div id="toppanel">

<!--Start MenuPanel Content--> 
<div id="panel">

<!--Start Panel Content - Clearfix with logo and content divs--> 
<div class="content clearfix">
<p><h1>FULLHAUS</h1></p>


<div id="LoggedIn">
<div id="LoggedInTitle">

</div>
</div>


<!-- tabs work as navigator for scrollable -->





  


</div>
<!--Start Panel Content - Clearfix with logo and content divs--> 

</div>
<!--End MenuPanel Content--> 


<!--Start Tab - Menu Panel Up/down-->  
<div class="tab">
        <ul class="login">
            <li class="left">&nbsp;</li>

            <li>NAME LASTNAME</li>
            <li class="sep">|</li>
            <li id="toggle"><a id="open" class="open" href="#">open menu</a><a id="close" style="display: none;" class="close" href="#">Stäng Meny</a></li>
            <li class="right">&nbsp;</li>
        </ul> 
    </div>
<!--End Tab - Menu Panel Up/down--> 
    
</div>

<!--End Sliding MenuPanel--> 

<div id="Container">
<div id="Header"></div>

<div id="Availability">
<div id="PanelHead"><h1>Availability</h1><p> Occ:<span class="HeadInfo">00,0%</span>Rate:<span class="HeadInfo">Std</span>Currency:<span class="HeadInfo">SEK</span></p></div>

<div id="PanelContent">

<script>
// What is $(document).ready ? See: http://flowplayer.org/tools/documentation/basics.html#document_ready
$(document).ready(function() {

$(".download").tooltip({ position: 'center right',delay: '0', offset: [0, -30]});
});
</script>

<span class="download">
<ul class="Link"> 
<li >
<a class="zoom3"  href="templates/tmp_editpropertinfo.html?iframe">
<span class="LeftSpace">
    <p>0</p>
</span>
<span class="RightSpace">
<h3>Presidential suite</h3>

<p>Discount:<span class="DiscComCol">200</span>commission:<span class="DiscComCol">15%</span></p>
</span>
</a>
</li>
</ul>
</span>
<!-- tooltip element -->
<div class="tooltip">

    <table style="margin:0">
        <tr>

            <td colspan="3"><h2>Presidential Suite</h2></td>
        </tr>
        <tr>
            <td>Free Rooms:</td>
            <td>Discount:</td>
            <td>Commission:</td>
        </tr>

        <tr>
            <td><form id="FreeRoom" name="FreeRoom" method="post" action="">
      <input type="text" name="test" id="FreeRoom" />
    </form></td>
<td><form id="FreeRoom" name="form1" method="post" action="">
      <input type="text" name="test" id="FreeRoom" />
    </form></td>
<td><form id="FreeRoom" name="form1" method="post" action="">
      <input type="text" name="test" id="FreeRoom" />
    </form></td>
        </tr>
    </table>
</div>

 
<ul class="AvailRooms"> 
<li>
  <span class="LeftSpace">
  <p>0</p></span>
  <span class="RightSpace">
  <h3>Total available</h3></span>

</li>
</ul> 
</div>
<div id="PanelInfo">Showing 10 of 10</div>

<div id="PanelFoot">foot</div>
</div>





<div id="Reservations">
<div id="PanelHead"><h1>Reservations</h1>

<p>Today:<span class="HeadInfo">0</span>Pending:<span class="HeadInfo">0</span></p></div>
<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>time</p>

  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>

</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>time</p>
  <p>00:00</p>

  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>

</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>

  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">

  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

</div>
<div id="PanelFoot">NEW RESERVATION</div>

</div>





<div id="Requests">
<div id="PanelHead">
<h1>sent Requests</h1><p>Today:<span class="HeadInfo">0</span>Pending:<span class="HeadInfo">0</span></p>
</div>
<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>Time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">

  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>

<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>

  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">

  <h3>Status</h3>
  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>

  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>

  <p>time</p>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Lastname, Firstname</h3>
  <p>X Roomtype, X p</p>
  <p>Source Hotel</p>

  </span>
</a>
</li>
</ul>

</div>

<div id="PanelFoot">foot</div>
</div>





<div id="Summary">

<div id="PanelHead"><h1>Summary</h1>
<p>City:<span class="HeadInfo">Stockholm</span>Area:<span class="HeadInfo">north</span></p></div>
<div id="PanelContent">

<ul class="Summary"> 
<li>
  <span class="LeftSpace">
  <p>0</p>
  <p>0.0%</p>

  <p>&nbsp;</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>
  <p>0</p>

  <p>0</p>
  </span>
  <span class="RightSpace">
  <p>Total amount of rooms</p>
  <p>Occupancy</p>
  <p>&nbsp;</p>
  <p>Available rooms</p>

  <p>Hotels with available rooms</p>
  <p>Occupied rooms</p>
  <p>Full hotels</p>
  <p>Overbooked rooms</p>
  <p>Overbooked hotels</p>
  </span>

</li>
</ul>
</div>
<div id="PanelFoot">foot</div>
</div>





<div id="Warnings">
<div id="PanelHead">
<h1>Warnings</h1>
<p>Today:<span class="HeadInfo">0</span>New:<span class="HeadInfo">0</span></p>

</div>
<div id="PanelContent">

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">

  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">

  <h3>Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>

</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>00:00</p>
  </span>

  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">

  <span class="LeftSpace">
  <h3>Status</h3>
  <p>00:00</p>
  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>

  </span>
</a>
</li>
</ul>

<ul class="Link"> 
<li>
<a href="#">
  <span class="LeftSpace">
  <h3>Status</h3>
  <p>00:00</p>

  </span>
  <span class="RightSpace">
  <h3>Warningtype</h3>
  <p>Source Hotel</p>
  </span>
</a>
</li>
</ul>


</div>
<div id="PanelFoot">foot</div>
</div>







</div>