<h1>Price definition of Room <?php echo $this->pageModel->room->name?>, Hotel <?php echo $this->pageModel->getHotel()->name?></h1>

<strong>Calendar:</strong>
<table border="0" cellspacing="0" cellpadding="0" width="800">
<tr>
<td>Period</td>
<td>Price</td>
</tr>
<?php 
foreach($this->pageModel->getCalendarPrices() as $calendarPriceDTO) {
?>
<tr>
<td><?php echo $calendarPriceDTO->calendar->name?> (<?php echo $calendarPriceDTO->calendar->from?> - <?php echo $calendarPriceDTO->calendar->to?>)</td>
<td><?php echo $calendarPriceDTO->price?></td>
</tr>
<?php }?>
</table>
<hr/>
<strong>Rate</strong>
