<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<?php
echo '<?xml version="1.0" encoding="UTF-8" />';
echo $this->doctype();
$config = Zend_Registry::get ( "config" );
?>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>FLLHAUS Direct booking system</title>
<meta name="description" content="FLLHAUS Direct booking system" />
<?php
$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/default.css' );
$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/jquery.fancybox-1.3.4.css' );
//$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/fancy.css' );
//$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/slide.css' );
//$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/styles.css' );
//$this->headLink ()->prependStylesheet ( $config->baseurl . '/css/template.css' );
				
$this->headScript ()->prependFile ( $config->baseurl . '/js/boxparameters.js' );
$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.fancybox-1.3.4.pack.js' );
//$this->headScript ()->prependFile ( $config->baseurl . '/js/menuslide/slide.js' );
$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.easing.1.3.js' );
$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.mousewheel-3.0.4.pack.js');
$this->headScript ()->prependFile ( $config->baseurl . '/js/jquery.1.4.3.min.js' );
echo $this->headLink ();

echo $this->headScript ();
?>
<script type="text/javascript">
var $ = jQuery.noConflict();

</script>
</head>

<body id="Bg"">
<?php
echo $this->layout ()->content;
?>
</body>


<!--Fancybox options-->
<script type="text/javascript">
$(document).ready(function() {
	/* This is basic - uses default settings */
	$("a#single_image").fancybox();
	
	/* Using custom settings */
	
	$("a#inline").fancybox({
		'hideOnContentClick': true
	});

	/* Apply fancybox to multiple items */
	
	$("a.various1").fancybox({
		'scrolling': 'yes',
		'width': 500,
		'autoScale' : true,
		'transitionIn' : 'none',
		'transitionOut' : 'none',
		'type' : 'iframe',
		'hideOnContentClick' : false,
		'onClosed': function() {
			parent.location.reload(true);
		} 
	});
	
}); 
</script>

<!--
<script type="text/javascript">
        $(document).ready(function() {
            $("a.zoom").fancybox();

            $("a.zoom1").fancybox({
                'overlayOpacity'    :   0.5,
                'frameWidth'        :   500,
                'frameHeight'       :   600,
                'overlayColor'      :   '#000'
            });

            $("a.zoom2").fancybox({
                'zoomSpeedIn'       :   500,
                'zoomSpeedOut'      :   500
            });
            
            $("a.zoom3").fancybox({
                'zoomOpacity'       :   1000,
                'overlayOpacity'    :   0.3,
                'zoomSpeedIn'       :   500,
                'zoomSpeedOut'      :   200,
                'frameWidth'        :   800,
                'overlayColor'      :   '#000',
                'padding'           :   0,
                'frameHeight'       :   630,
                'autoDimensions'    :   false
                
                
            });
        });
</script>

<script type="text/javascript">
        $(document).ready(function(){
        $("input, textarea").addClass("idle");
            $("input, textarea").focus(function(){
                $(this).addClass("activeField").removeClass("idle");
        }).blur(function(){
                $(this).removeClass("activeField").addClass("idle");
        });
        });
</script>
-->
</html>