<?php if($this->totalItemCount!=0){ ?>  
 
<div class="explainLine" style="float:left;width:880px;">
 <div class="pagination">
        
 <div class="paginationInfo">
       
      Showing <?php echo $this->firstItemNumber?>-<?php echo $this->lastItemNumber;?> of  <?php echo $this->totalItemCount; ?> results
       <!-- <?php echo $this->current; ?>/<?php echo  $this->last; ?>  -->  
 </div>
 
 
 <div class="paginationNumbers">
    <div class="pagePrev">
        <!-- First page link 
        <?php if (isset($this->previous)): ?>
          <a href="<?php echo  $this->url(array('page' => $this->first), "default", false); ?>">首页</a> 
    <?php endif; ?>-->
        <!-- Previous page link -->
    	<?php if (isset($this->previous)): ?>
              <a href="<?php echo  $this->url(array('page' => $this->previous), "default", false); ?>">Prev</a> 
              <?php endif; ?>
        </div>
        
        <!-- Numbered page links -->
        <div class="pageNumbers">
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page), "default", false); ?>"><?php echo $page; ?></a>
            <?php else: ?>
            <span>
                <?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
        
        <div class="pageNext">
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
               <a href="<?php echo $this->url(array('page' => $this->next), "default", false); ?>">Next </a> 
         <?php endif; ?>      
        <!-- Last page link 
        <?php if (isset($this->next)): ?>
              <a href="<?php echo  $this->url(array('page' => $this->last), "default", false); ?>">末页</a>
        <?php endif; ?>-->
        </div>
        </div>
        
 </div></div>
 <?php }?>